build: remove csstype from dependencies
This fixes a conflict with react and typescript. src/Link.tsx(77,14): error TS2742: The inferred
type of 'Link' cannot be named without a reference to 'react/node_modules/csstype'. This is likely
not portable. A type annotation is necessary.